In [1]:
import pandas as pd
import joblib

In [2]:
# 모듈을 호출하여 신규 데이터를 예측해보기

# 신규 데이터 : 나이 : 35, 성별 : 남, 연소득 : 5000, 근속연수 : 8, 주거형태 : 자가, 신용점수 : 720,
# 기존대출건수 : 1, 연간카드사용액 : 2400, 부채비율 : 25.0, 대출신청액 : 3000, 대출목적 : 주택구입, 상환방식 : 원리금균등, 대출기간 : 36

# Module Load
pipe = joblib.load('../models/loan_pipeline.pkl')
encoders = joblib.load('../models/label_encoders.pkl')
cols_name = joblib.load('../models/feature_names.pkl')

In [3]:
# Inference
sample_input = {
    "나이": 35,
    "성별": "남",
    "연소득": 5000,
    "근속연수": 8,
    "주거형태": "자가",
    "신용점수": 720,
    "기존대출건수": 1,
    "연간카드사용액": 2400,
    "부채비율": 25.0,
    "대출신청액": 3000,
    "대출목적": "주택구입",
    "상환방식": "원리금균등",
    "대출기간": 36
}

df_sample = pd.DataFrame([sample_input])

### Encoder Module : feature wise
> column transformer를 현업에서 활용한다고 함

In [6]:
cat_cols = ['주거형태', '성별', '대출목적', '상환방식']

# Before
print('before : \n')
display(df_sample)

# Logics
for col in cat_cols:
    df_sample[col] = encoders[col].transform(df_sample[col])

# After
print('after : \n')
display(df_sample)

before :

,나이,성별,연소득,근속연수,주거형태,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출목적,상환방식,대출기간
0,35,남,5000,8,자가,720,1,2400,25.0,3000,주택구입,원리금균등,36

after :

,나이,성별,연소득,근속연수,주거형태,신용점수,기존대출건수,연간카드사용액,부채비율,대출신청액,대출목적,상환방식,대출기간
0,35,0,5000,8,1,720,1,2400,25.0,3000,6,2,36

### Inference Module : Pipeline

In [8]:
sample_pred = pipe.predict(df_sample)
print('예측한 값 : ', sample_pred)

예측한 값 :  [1]